<?php

namespace Entity\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitySecuredObjectProxy extends \Entity\SecuredObject implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setDefaultValues()
    {
        $this->_load();
        return parent::setDefaultValues();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function getClass()
    {
        $this->_load();
        return parent::getClass();
    }

    public function setClass($class)
    {
        $this->_load();
        return parent::setClass($class);
    }

    public function getMethod()
    {
        $this->_load();
        return parent::getMethod();
    }

    public function setMethod($method)
    {
        $this->_load();
        return parent::setMethod($method);
    }

    public function getAllowed()
    {
        $this->_load();
        return parent::getAllowed();
    }

    public function setAllowed($allowed)
    {
        $this->_load();
        return parent::setAllowed($allowed);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'class', 'method', 'allowed');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}