<?php

namespace Entity\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityRoleProxy extends \Entity\Role implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getUsers()
    {
        $this->_load();
        return parent::getUsers();
    }

    public function setUsers($users)
    {
        $this->_load();
        return parent::setUsers($users);
    }

    public function getSecuredObjects()
    {
        $this->_load();
        return parent::getSecuredObjects();
    }

    public function setSecuredObjects($securedObjects)
    {
        $this->_load();
        return parent::setSecuredObjects($securedObjects);
    }

    public function addSecuredObject($securedObject)
    {
        $this->_load();
        return parent::addSecuredObject($securedObject);
    }

    public function getAcls()
    {
        $this->_load();
        return parent::getAcls();
    }

    public function setAcls($acls)
    {
        $this->_load();
        return parent::setAcls($acls);
    }

    public function addAcl($acl)
    {
        $this->_load();
        return parent::addAcl($acl);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'users', 'securedObjects', 'acls');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}